local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Shared")
require(Shared:WaitForChild("Remotes"))

local PlayerScripts = Players.LocalPlayer:WaitForChild("PlayerScripts")
local FPSCamera = require(PlayerScripts:WaitForChild("FPSCamera"))
local WeaponController = require(PlayerScripts:WaitForChild("WeaponController"))
local HUDController = require(PlayerScripts:WaitForChild("HUDController"))
local AbilityController = require(PlayerScripts:WaitForChild("AbilityController"))
local BuyMenuController = require(PlayerScripts:WaitForChild("BuyMenuController"))
local MatchUIController = require(PlayerScripts:WaitForChild("MatchUIController"))
local KillCamController = require(PlayerScripts:WaitForChild("KillCamController"))
local VFXController = require(PlayerScripts:WaitForChild("VFXController"))
local KillfeedController = require(PlayerScripts:WaitForChild("KillfeedController"))
local DamageNumberController = require(PlayerScripts:WaitForChild("DamageNumberController"))
local ViewmodelController = require(PlayerScripts:WaitForChild("ViewmodelController"))
local SoundController = require(PlayerScripts:WaitForChild("SoundController"))
local ADSController = require(PlayerScripts:WaitForChild("ADSController"))
local SkinEffectsController = require(PlayerScripts:WaitForChild("SkinEffectsController"))
local MinimapController = require(PlayerScripts:WaitForChild("MinimapController"))
local ScoreboardController = require(PlayerScripts:WaitForChild("ScoreboardController"))
local AgentSelectController = require(PlayerScripts:WaitForChild("AgentSelectController"))
local SpikeInteractionController = require(PlayerScripts:WaitForChild("SpikeInteractionController"))
local SettingsController = require(PlayerScripts:WaitForChild("SettingsController"))
local LobbyController = require(PlayerScripts:WaitForChild("LobbyController"))
local NametagController = require(PlayerScripts:WaitForChild("NametagController"))
local InventoryController = require(PlayerScripts:WaitForChild("InventoryController"))
local PingController = require(PlayerScripts:WaitForChild("PingController"))
local SpectatorController = require(PlayerScripts:WaitForChild("SpectatorController"))
local MapVoteController = require(PlayerScripts:WaitForChild("MapVoteController"))
local MovementController = require(PlayerScripts:WaitForChild("MovementController"))
local CombatReportController = require(PlayerScripts:WaitForChild("CombatReportController"))
local AchievementController = require(PlayerScripts:WaitForChild("AchievementController"))
local DailyChallengeController = require(PlayerScripts:WaitForChild("DailyChallengeController"))
local LeaderboardController = require(PlayerScripts:WaitForChild("LeaderboardController"))
local TutorialController = require(PlayerScripts:WaitForChild("TutorialController"))
local FootstepController = require(PlayerScripts:WaitForChild("FootstepController"))
local BattlePassController = require(PlayerScripts:WaitForChild("BattlePassController"))
local CareerStatsController = require(PlayerScripts:WaitForChild("CareerStatsController"))
local ToastController = require(PlayerScripts:WaitForChild("ToastController"))
local DamageIndicatorController = require(PlayerScripts:WaitForChild("DamageIndicatorController"))
local WeaponDropController = require(PlayerScripts:WaitForChild("WeaponDropController"))
local PerformanceController = require(PlayerScripts:WaitForChild("PerformanceController"))
local ChatController = require(PlayerScripts:WaitForChild("ChatController"))
local AbilityHUDController = require(PlayerScripts:WaitForChild("AbilityHUDController"))
local WeaponSlotController = require(PlayerScripts:WaitForChild("WeaponSlotController"))
local WeaponInspectController = require(PlayerScripts:WaitForChild("WeaponInspectController"))
local SpikeUrgencyController = require(PlayerScripts:WaitForChild("SpikeUrgencyController"))
local SpikeTimerHUDController = require(PlayerScripts:WaitForChild("SpikeTimerHUDController"))
local LowHPController = require(PlayerScripts:WaitForChild("LowHPController"))
local RoundCounterController = require(PlayerScripts:WaitForChild("RoundCounterController"))
local CompendiumController = require(PlayerScripts:WaitForChild("CompendiumController"))

FPSCamera.Start()
WeaponController.Start()
HUDController.Start()
AbilityController.Start()
BuyMenuController.Start()
MatchUIController.Start()
KillCamController.Start()
VFXController.Start()
KillfeedController.Start()
DamageNumberController.Start()
ViewmodelController.Start()
SoundController.Start()
ADSController.Start()
SkinEffectsController.Start()
MinimapController.Start()
ScoreboardController.Start()
AgentSelectController.Start()
SpikeInteractionController.Start()
SettingsController.Start()
LobbyController.Start()
NametagController.Start()
InventoryController.Start()
PingController.Start()
SpectatorController.StartListening()
MapVoteController.Start()
MovementController.Start()
CombatReportController.Start()
AchievementController.Start()
DailyChallengeController.Start()
LeaderboardController.Start()
TutorialController.Start()
FootstepController.Start()
BattlePassController.Start()
CareerStatsController.Start()
ToastController.Start()
DamageIndicatorController.Start()
WeaponDropController.Start()
PerformanceController.Start()
ChatController.Start()
AbilityHUDController.Start()
WeaponSlotController.Start()
WeaponInspectController.Start()
SpikeUrgencyController.Start()
SpikeTimerHUDController.Start()
LowHPController.Start()
RoundCounterController.Start()
CompendiumController.Start()

print("[Client] Roblox Valorant MVP loaded")
